import Image from "next/image";
import Link from "next/link";
import { Brand } from "@/components/Brand";
import { MarketTicker } from "@/components/MarketTicker";

const pillars = [
  ["01", "Predict", "Ask better questions.", "Explore a market thesis with AI research. Separate evidence, assumptions, and what still needs confirmation."],
  ["02", "Analyze", "See the whole setup.", "Bring your own observations to the research workspace. Live market data awaits a verified broker integration."],
  ["03", "Manage risk", "Know your downside.", "Calculate position size from your capital, entry, stop, and risk budget before considering a trade."],
  ["04", "Execute & automate", "Stay in control.", "Execution and automation are future capabilities. This release is read-only, with live orders disabled."],
];

export default function Home() {
  return <main className="gnk-site">
    <a className="skip-link" href="#main-content">Skip to content</a>
    <nav className="gnk-nav" aria-label="Main navigation"><Brand /><div className="gnk-nav-links"><a href="#platform">Platform</a><a href="#intelligence">AI workspace</a><a href="#risk">Risk first</a></div><div className="gnk-nav-actions"><Link href="/login">Sign in</Link><Link className="gnk-button primary" href="/register">Open your workspace <span>↗</span></Link></div></nav>
    <MarketTicker />
    <section className="gnk-hero" id="main-content">
      <div className="hero-kicker"><span className="status-dot" /> BUILT FOR THE INDIAN MARKET <span className="pill">READ-ONLY RELEASE</span></div>
      <div className="gnk-hero-grid"><div className="gnk-hero-copy"><h1>Intelligence<br />behind<br /><span>every trade.</span></h1><p>A sharper research workspace. A clearer view of risk. Your next decision, with more perspective.</p><div className="gnk-hero-actions"><Link href="/register" className="gnk-button primary">Start with a clearer view <span>↗</span></Link><a href="#platform" className="gnk-button ghost">Explore the platform <span>↓</span></a></div><div className="hero-footnote"><span>AI-assisted research</span><span>Risk planning</span><span>Secure account access</span></div></div>
      <div className="brand-stage"><div className="stage-top"><span>GNK ALGO / THE MARKET MINDSET</span><span>↗</span></div><Image src="/gnk-algo-brand.jpg" alt="GNK ALGO bull and bear artwork: Intelligence behind every trade" width={1672} height={943} priority sizes="(max-width: 900px) 100vw, 55vw" /><div className="stage-bottom"><span><i className="status-dot" /> RESEARCH. REFINE. REPEAT.</span><span>NSE · BSE · MCX</span></div><div className="floating-note"><span className="spark">✳</span><div><small>THE EDGE IS IN YOUR PROCESS</small><strong>Think clearly. Trade deliberately.</strong></div></div></div></div>
    </section>
    <section className="platform-section" id="platform"><div className="section-heading"><div><p className="gnk-eyebrow">YOUR PROCESS, CONNECTED</p><h2>From a question<br />to a considered decision.</h2></div><p>Keep research, position sizing, and account access in one focused workspace. Know exactly which tools are ready.</p></div><div className="pillar-grid">{pillars.map(([number, title, heading, body]) => <article key={number} className="pillar"><div className="pillar-top"><span>{number}</span><span>↗</span></div><p className="gnk-eyebrow">{title}</p><h3>{heading}</h3><p>{body}</p></article>)}</div></section>
    <section className="intelligence-section" id="intelligence"><div><p className="gnk-eyebrow">A SECOND PERSPECTIVE</p><h2>Your research.<br /><span>A little more intelligent.</span></h2><p>Turn a question into a structured research brief. Explore your thesis, review its assumptions, and identify the evidence you still need.</p><Link href="/dashboard" className="gnk-button primary">Explore AI research <span>↗</span></Link><p className="small-note">Available after the operator configures an AI provider. No live market access or order execution.</p></div><div className="research-preview"><div className="preview-label"><span>✳ GNK INTELLIGENCE</span><span className="pill">WORKFLOW PREVIEW</span></div><h3>What could invalidate<br />my market thesis?</h3><div className="research-step"><b>01</b><div><strong>State the thesis</strong><p>Describe the market, timeframe, and your observations.</p></div><span>↗</span></div><div className="research-step"><b>02</b><div><strong>Challenge the assumptions</strong><p>Separate what you know from what you expect.</p></div><span>↗</span></div><div className="research-step"><b>03</b><div><strong>Define the next check</strong><p>Identify evidence before acting on a conclusion.</p></div><span>↗</span></div><div className="preview-bottom">AI output needs your review. No return guarantees.</div></div></section>
    <section className="risk-section" id="risk"><div className="risk-symbol" aria-hidden="true">⌁</div><div><p className="gnk-eyebrow">RISK BEFORE REWARD</p><h2>A good setup starts<br />with a defined downside.</h2><p>Plan risk using your own inputs. Broker access, market data, and live execution each need independent verification.</p></div><Link href="/dashboard" className="gnk-button ghost">Plan your risk <span>↗</span></Link></section>
    <section className="closing-section"><p className="gnk-eyebrow">MAKE SPACE FOR BETTER DECISIONS</p><h2>Your next chapter<br />starts with clarity.</h2><Link href="/register" className="gnk-button primary">Create your account <span>↗</span></Link></section>
    <footer className="gnk-footer"><div><Brand /><p>Intelligence behind every trade.</p></div><div><Link href="/login">Member sign in ↗</Link><a href="#platform">Platform ↑</a></div><p>© 2026 GNK ALGO<br />Research tools, not investment advice.<br />Trading involves risk. Live execution is disabled.</p></footer>
  </main>;
}
